version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_lab2
    ports:
      - '27017:27017'
  sharing:
    image: bike-sharing-mongo:0.1.0
    build:
      context: .
    container_name: sharing-mongo
    ports:
      - '80:8080'
