version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_lab2
    ports:
      - '27017:27017'
  sharing:
    image: bike-sharing-mongo:0.2.0
    build:
      context: .
    container_name: sharing-mongo
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_MONGODB_DATABASE: bikeService
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_AUTO-INDEX-CREATION: true