apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    type: deployment
    app: mongo
    kind: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      type: container
  template:
    metadata:
      labels:
        app: mongo
        type: container
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              protocol: TCP
              name: mongo-port