apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-sharing-deployment
  labels:
    type: deployment
    app: sharing-service
    db: mongo
    kind: app
spec:
  replicas: 2
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: sharing
      type: container
  template:
    metadata:
      labels:
        app: sharing
        type: container
    spec:
      containers:
        - name: sharing-service
          image: bike-sharing-mongo:0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP
              name: sharing-port
          env:
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db_mongo_name
                  name: configmapSharing
            - name: SPRING_DATA_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  key: db_mongo_port
                  name: configmapSharing
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_mongo_host
                  name: configmapSharing
            - name: SPRING_DATA_MONGODB_AUTO-INDEX-CREATION
              valueFrom:
                configMapKeyRef:
                  key: db_mongo_auto_index_creation
                  name: configmapSharing